CREATE OR REPLACE FUNCTION stat.normalize_index_expression(IN in_string text,IN in_id bigint,IN in_l integer)
    RETURNS text
    LANGUAGE 'plpgsql'
    IMMUTABLE
    PARALLEL UNSAFE
    COST 100
    
AS $BODY$
BEGIN
    RETURN rpad(normalize_string(in_string),in_l,' ') || lpad(in_id::text,20,'0');
END;
$BODY$;


-- Table: stat.division

-- DROP TABLE stat.division;

CREATE TABLE stat.division
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    parent_id bigint,
    organization_id bigint,
    name text COLLATE pg_catalog."default" NOT NULL,
    short_name text COLLATE pg_catalog."default" NOT NULL,
    prefix character varying(10) COLLATE pg_catalog."default",
    oid character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT division_pkey PRIMARY KEY (id),
    CONSTRAINT division_organization_id_fkey FOREIGN KEY (organization_id)
        REFERENCES stat.organization (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT division_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES stat.division (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE stat.division
    OWNER to stat;

COMMENT ON TABLE stat.division
    IS 'Справочник подразделений';

COMMENT ON COLUMN stat.division.id
    IS 'Уникальный ключ для подразделений';

COMMENT ON COLUMN stat.division.parent_id
    IS 'Ссылка на родительское подразделение';

COMMENT ON COLUMN stat.division.organization_id
    IS 'Ссылка на организацию к которой относится подразделение';

COMMENT ON COLUMN stat.division.name
    IS 'Наименование подразделения';

COMMENT ON COLUMN stat.division.short_name
    IS 'Сокращенное наименование подразделения';

COMMENT ON COLUMN stat.division.prefix
    IS 'Префикс подразделения (например для выгрузки в бухгалтерию)';
-- Index: division_name_btree_idx

-- DROP INDEX stat.division_name_btree_idx;

CREATE INDEX division_name_btree_idx
    ON stat.division USING btree
    (stat.normalize_string(name::text) COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

COMMENT ON INDEX stat.division_name_btree_idx
    IS 'Индекс для поиска по полному совпадению наименования в таблице подразделения организации';
-- Index: division_name_gin_idx

-- DROP INDEX stat.division_name_gin_idx;

CREATE INDEX division_name_gin_idx
    ON stat.division USING gin
    (stat.normalize_string(name::text) COLLATE pg_catalog."default" gin_trgm_ops)
    TABLESPACE pg_default;

COMMENT ON INDEX stat.division_name_gin_idx
    IS 'Индекс для поиска по вхождению подстроки в наименование в таблице подразделения организации';
-- Index: division_oid_btree_idx

-- DROP INDEX stat.division_oid_btree_idx;

CREATE INDEX division_oid_btree_idx
    ON stat.division USING btree
    (oid COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

COMMENT ON INDEX stat.division_oid_btree_idx
    IS 'Индекс для поиска по точному совпадению OID в таблице подразделения организации';
-- Index: division_page_navigation_btree_idx

-- DROP INDEX stat.division_page_navigation_btree_idx;

CREATE INDEX division_page_navigation_btree_idx
    ON stat.division USING btree
    (stat.normalize_index_expression(name::text, id, 100) COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;