-- Table: stat.auth_position

-- DROP TABLE stat.auth_position;

CREATE TABLE stat.auth_position
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default",
    parent_id bigint,
    sort bigint,
    normative bigint,
    -- form_30 bigint,
    sert boolean,
    actual boolean,
    comment text COLLATE pg_catalog."default",
    p_group boolean,
    data_end date,
    CONSTRAINT auth_position_pkey PRIMARY KEY (id),
    CONSTRAINT auth_position_auth_position_id_fkey FOREIGN KEY (parent_id)
        REFERENCES stat.auth_position (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE stat.auth_position
    OWNER to stat;

COMMENT ON TABLE stat.auth_position
    IS 'Таблица должностей пользователей';

COMMENT ON COLUMN stat.auth_position.id
    IS 'Уникальный идентификатор должности пользователя';

COMMENT ON COLUMN stat.auth_position.name
    IS 'Наименование должности';

COMMENT ON COLUMN stat.auth_position.parent_id
    IS 'Ссылка на элемент-родитель данного справочника';

COMMENT ON COLUMN stat.auth_position.sort
    IS 'Порядок сортировки строк в исходном справочнике';

--COMMENT ON COLUMN stat.auth_position.normative
--    IS 'Признак соответсвия НПА, число от 1 до 5';

-- COMMENT ON COLUMN stat.auth_position.form_30
--    IS 'Код по отчетной статистической Форме № 30';

COMMENT ON COLUMN stat.auth_position.sert
    IS 'Признак наличия сертификата';

COMMENT ON COLUMN stat.auth_position.actual
    IS 'Признак акутальности записи';

COMMENT ON COLUMN stat.auth_position.comment
    IS 'Комментарий';

COMMENT ON COLUMN stat.auth_position.p_group
    IS 'Признак группировочных записей';

COMMENT ON COLUMN stat.auth_position.data_end
    IS 'Дата окончания действия записи';
-- Index: auth_position_data_end_btree_idx

-- DROP INDEX stat.auth_position_data_end_btree_idx;

CREATE INDEX auth_position_data_end_btree_idx
    ON stat.auth_position USING btree
    (data_end ASC NULLS LAST)
    TABLESPACE pg_default
    WHERE data_end IS NOT NULL;

COMMENT ON INDEX stat.auth_position_data_end_btree_idx
    IS 'Индекс для ограничения выборки профессий по дате актуальности';
-- Index: auth_position_name_btree_idx

-- DROP INDEX stat.auth_position_name_btree_idx;

CREATE INDEX auth_position_name_btree_idx
    ON stat.auth_position USING btree
    (stat.normalize_string(name::text) COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: auth_position_name_gin_idx

-- DROP INDEX stat.auth_position_name_gin_idx;

CREATE INDEX auth_position_name_gin_idx
    ON stat.auth_position USING gin
    (stat.normalize_string(name::text) COLLATE pg_catalog."default" gin_trgm_ops)
    TABLESPACE pg_default;
-- Index: fki_auth_position_auth_position_id_fkey

-- DROP INDEX stat.fki_auth_position_auth_position_id_fkey;

CREATE INDEX fki_auth_position_auth_position_id_fkey
    ON stat.auth_position USING btree
    (parent_id ASC NULLS LAST)
    TABLESPACE pg_default;