-- Table: stat.input_file

-- DROP TABLE stat.input_file;

CREATE TABLE stat.input_file
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    template_id bigint,
    organization_id bigint,
    division_id bigint,
    uuid uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    path text COLLATE pg_catalog."default" NOT NULL,
    period date NOT NULL,
    status jsonb NOT NULL DEFAULT '{"handled": false, "validation": false}'::jsonb,
    auth_user_id bigint,
    deleted boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    data jsonb,
    protocol_errors jsonb,
    CONSTRAINT input_file_pkey PRIMARY KEY (id),
    CONSTRAINT input_file_auth_user_id_fkey FOREIGN KEY (auth_user_id)
        REFERENCES stat.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT input_file_organization_id_fkey FOREIGN KEY (organization_id)
        REFERENCES stat.organization (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE stat.input_file
    OWNER to stat;

COMMENT ON TABLE stat.input_file
    IS 'Файл входящий на проверку';

COMMENT ON COLUMN stat.input_file.id
    IS 'Ид. фходящего файла';

COMMENT ON COLUMN stat.input_file.template_id
    IS 'Ид. шаблона входящего файла';

COMMENT ON COLUMN stat.input_file.organization_id
    IS 'Ид. организации';

COMMENT ON COLUMN stat.input_file.division_id
    IS 'Ид. подразделения';

COMMENT ON COLUMN stat.input_file.uuid
    IS 'UUID присвоенное фходящем файлу в системе';

COMMENT ON COLUMN stat.input_file.name
    IS 'Наименование оригинала входящего файла';

COMMENT ON COLUMN stat.input_file.path
    IS 'Путь хранения зарженного файла в системе';

COMMENT ON COLUMN stat.input_file.period
    IS 'Дата расчетного периода ';

COMMENT ON COLUMN stat.input_file.status
    IS 'Статус проверки файла validation=true - валидация пройдена успешно, handled=true ручная операция разрешения на отправку файла';

COMMENT ON COLUMN stat.input_file.auth_user_id
    IS 'Ид.пользователя загрузившего файл';

COMMENT ON COLUMN stat.input_file.deleted
    IS 'Признак удаления записи шаблона';

COMMENT ON COLUMN stat.input_file.created_at
    IS 'Дата записи';

COMMENT ON COLUMN stat.input_file.deleted_at
    IS 'Дата удаления';

COMMENT ON COLUMN stat.input_file.data
    IS 'Данные загружаемого файла';

COMMENT ON COLUMN stat.input_file.protocol_errors
    IS 'Протокол ошибок валидации данных';
-- Index: fki_input_file_auth_user_id_fkey

-- DROP INDEX stat.fki_input_file_auth_user_id_fkey;

CREATE INDEX fki_input_file_auth_user_id_fkey
    ON stat.input_file USING btree
    (auth_user_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: stat_input_file_uuid_btree_idx

-- DROP INDEX stat.stat_input_file_uuid_btree_idx;

CREATE INDEX stat_input_file_uuid_btree_idx
    ON stat.input_file USING btree
    (uuid ASC NULLS LAST)
    TABLESPACE pg_default;

COMMENT ON INDEX stat.stat_input_file_uuid_btree_idx
    IS 'Индекс для поиска по уникальному UUID';

-- Rule: delete_stat_input_file ON stat.input_file

-- DROP Rule delete_stat_input_file ON stat.input_file;

CREATE OR REPLACE RULE delete_stat_input_file AS
    ON DELETE TO stat.input_file
    DO INSTEAD
(UPDATE input_file SET deleted = true, deleted_at = now()
  WHERE (input_file.id = old.id)
  RETURNING input_file.id,
    input_file.template_id,
    input_file.organization_id,
    input_file.division_id,
    input_file.uuid,
    input_file.name,
    input_file.path,
    input_file.period,
    input_file.status,
    input_file.auth_user_id,
    input_file.deleted,
    input_file.created_at,
    input_file.deleted_at,
    input_file.data,
    input_file.protocol_errors
);