-- Table: stat.type_report

-- DROP TABLE stat.type_report;

CREATE TABLE stat.type_report
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    deleted boolean DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    CONSTRAINT type_report_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE stat.type_report
    OWNER to stat;

COMMENT ON TABLE stat.type_report
    IS 'Тип отчетности';

COMMENT ON COLUMN stat.type_report.id
    IS 'Ид. типа отчетности';

COMMENT ON COLUMN stat.type_report.name
    IS 'Наименование шаблона';

COMMENT ON COLUMN stat.type_report.deleted
    IS 'Признак удаления записи шаблона';

COMMENT ON COLUMN stat.type_report.created_at
    IS 'Дата записи';

COMMENT ON COLUMN stat.type_report.deleted_at
    IS 'Дата удаления';

-- Rule: delete_stat_type_report ON stat.type_report

-- DROP Rule delete_stat_type_report ON stat.type_report;

CREATE OR REPLACE RULE delete_stat_type_report AS
    ON DELETE TO stat.type_report
    DO INSTEAD
(UPDATE type_report SET deleted = true, deleted_at = now()
  WHERE (type_report.id = old.id));


-- Rule: update_stat_type_report ON stat.type_report

-- DROP Rule update_stat_type_report ON stat.type_report;

CREATE OR REPLACE RULE update_stat_type_report AS
    ON UPDATE TO stat.type_report
    DO INSTEAD NOTHING;