CREATE USER stat WITH PASSWORD 'stat';

GRANT ALL PRIVILEGES ON DATABASE stat TO stat;

CREATE SCHEMA stat;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA stat TO stat;

DROP DATABASE IF EXISTS stat;
CREATE DATABASE stat;
ALTER DATABASE stat SET timezone TO 'Europe/Moscow';
\c stat;
CREATE EXTENSION pg_trgm;
CREATE EXTENSION ltree;